[package]
name = "yane"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_hex = "0.4.1"
cargo-insta = "1.41.1"
glow = "0.14.1"
imgui = "0.12.0"
imgui-glow-renderer = "0.13.0"
imgui-sdl2-support = "0.13.0"
log = "0.4.22"
rand = "0.8.5"
rubato = "0.16.1"
sdl2 = "0.37.0"
simplelog = "0.12.2"
test-case = "3.3.1"

[features]
default = ["gui"]
gui = []

[dev-dependencies]
insta = "1.41.1"
